version: '3.8'

services:
  secure-app:
    image: projetdevsecops-secure-app
    ports:
      - "8081:80"
    networks:
      - security-net

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    networks:
      - security-net

networks:
  security-net:
    driver: bridge