@'
input {
  beats {
    port => 5044
  }
  http {
    port => 5000
  }
}

filter {
  # Détection Brute Force
  if [message] =~ "Login failed" or [message] =~ "401" {
    mutate {
      add_tag => ["bruteforce_attempt"]
    }
  }
  
  # Détection SQL Injection
  if [message] =~ "(?i)(SELECT|UNION|DROP|INSERT|--)" {
    mutate {
      add_tag => ["sql_injection"]
    }
  }
  
  # Extraire l'IP
  grok {
    match => { "message" => "%{IP:client_ip}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
'@ | Out-File -FilePath elk\logstash\pipeline\logstash.conf -Encoding UTF8